### ISSUE TITLE
Where does dagger2 get mainvView?

### ISSUE THREAD

**Issue by ysmintor** [iammert/dagger-android-injection#2]
```java
 @Provides
 MainPresenter provideMainPresenter(MainView mainView, ApiService apiService){
 return new MainPresenterImpl(mainView, apiService);
 }
```

I don't find any Inject of mainView, Where could Dagger2 to find it and then to provide MainPresenter?

**Comment by ysmintor** [comment]
Also I want to ask about the how to Inject specific `Retrofit2` like a different base url in that Activity to provide, So How could Dagger2 solve this problem?

**Comment by iammert** [comment]
@ysmintor When you inject into your activity, your activity will be attached to your dagger graph. Then you can provide your mainView with your activity. Actually, It is already defined in [MainActivityModule](https://github.com/iammert/dagger-android-injection/blob/master/app/src/main/java/iammert/com/dagger_android_injection/ui/main/MainActivityModule.java#L14)

**Comment by ysmintor** [comment]
@iammert 
After a while I saw the code in MainPresenterImpl.
```java

   @Inject
   public MainPresenterImpl(MainView mainView, ApiService apiService) {
   this.mainView = mainView;
   this.apiService = apiService;
   }
```

So for the mainView, I have to add a `MainViewImpl` and add @Inject above its contructor to let Dagger2 inject?

**Comment by iammert** [comment]
Yes. I suggest you read https://google.github.io/dagger/ .
