### ISSUE TITLE
Redundant presenter provides

### ISSUE THREAD

**Issue by badoualy** [iammert/dagger-android-injection#7]
You're providing the presenter via
https://github.com/iammert/dagger-android-injection/blob/dagger-simplified-with-contributes/app/src/main/java/iammert/com/dagger_android_injection/ui/detail/DetailActivityModule.java#L18

while having the `@Inject` annotation in the constructor, any reason?

**Comment by Sottti** [comment]
I came to ask this exactly. What is the  '@Inject' for?
